name: Deploy Example Projects
on:
  push:
    branches:
      - main
jobs:
  deno-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno run -A -- examples/discobot/main.ts --upload
